apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi-container
          image: your-dockerhub-username/fastapi-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "fastapi_db"
            - name: DB_USER
              value: "fastapi_user"
            - name: DB_PASSWORD
              value: "securepassword"
