apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
data:
  elasticsearch.yml: |
    cluster.name: elasticsearch-cluster
    network.host: 0.0.0.0
    discovery.type: single-node
    xpack.security.enabled: true
    xpack.monitoring.enabled: true
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secrets
type: Opaque
stringData:
  elastic-password: "elastic123secure"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  serviceName: elasticsearch-service
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      serviceAccountName: elasticsearch-sa
      imagePullSecrets:
        - name: default-secret
      initContainers:
      - name: install-kubectl
        image: bitnami/kubectl
        command:
        - sh
        - -c
        - |
          cp /opt/bitnami/kubectl/bin/kubectl /shared/kubectl && chmod +x /shared/kubectl
        volumeMounts:
        - name: shared-bins
          mountPath: /shared
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
        - name: discovery.type
          value: single-node
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-secrets
              key: elastic-password
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: PATH
          value: "/usr/share/elasticsearch/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/shared"
        lifecycle:
          postStart:
            exec:
              command:
              - bash
              - -c
              - |
                #!/bin/bash
                until curl -s -k "http://localhost:9200" > /dev/null; do 
                  echo "Waiting for Elasticsearch to start..."
                  sleep 10
                done
                echo "Creating Kibana service account..."
                curl -s -k -X POST -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" "http://localhost:9200/_security/service/elastic/kibana/credential/token/kibana-token" > /tmp/token.json
                TOKEN=$(cat /tmp/token.json | grep -o '"value":"[^"]*"' | cut -d'"' -f4)
                if [ ! -z "$TOKEN" ]; then
                  echo "Token created, creating secret..."
                  /shared/kubectl create secret generic kibana-token-secret --from-literal=token=$TOKEN -o yaml --dry-run=client | /shared/kubectl apply -f -
                else
                  echo "Failed to create token"
                  exit 1
                fi
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 30Gi
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  selector:
    app: elasticsearch
  ports:
  - port: 9200
    targetPort: 9200
    name: http
  - port: 9300
    targetPort: 9300
    name: transport
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      serviceAccountName: kibana-sa
      imagePullSecrets:
        - name: default-secret
      initContainers:
      - name: wait-for-elasticsearch
        image: bitnami/kubectl
        command:
        - sh
        - -c
        - |
          until kubectl get secret kibana-token-secret; do
            echo "Waiting for Elasticsearch to create Kibana token..."
            sleep 10
          done
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.10.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch-service:9200"
        - name: ELASTICSEARCH_SERVICEACCOUNT_TOKEN
          valueFrom:
            secretKeyRef:
              name: kibana-token-secret
              key: token
        - name: XPACK_SECURITY_ENABLED
          value: "true"
        - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
          value: "none"
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
spec:
  selector:
    app: kibana
  ports:
  - port: 5601
    targetPort: 5601
  type: LoadBalancer
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:8.10.1
        volumeMounts:
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: filebeat-config
        configMap:
          name: filebeat-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/lib/docker/containers/*/*.log
    output.elasticsearch:
      hosts: ["elasticsearch-service:9200"]
      username: "elastic"
      password: "${ELASTIC_PASSWORD}"
    setup.kibana:
      host: "kibana-service:5601" 