apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secrets
  namespace: default
type: Opaque
stringData:
  api-key: "secure-api-key"
  postgres-db: "fastapi_db"
  postgres-user: "fastapi_user"
  postgres-password: "securepassword" 