apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secrets
  namespace: default
type: Opaque
data:
  api-key: c2VjdXJlLWFwaS1rZXk=  # secure-api-key
  postgres-db: ZmFzdGFwaV9kYg==  # fastapi_db
  postgres-user: ZmFzdGFwaV91c2Vy  # fastapi_user
  postgres-password: c2VjdXJlcGFzc3dvcmQ=  # securepassword 