apiVersion: v1
kind: ServiceAccount
metadata:
  name: kibana-sa
  namespace: logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kibana-role
  namespace: logging
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kibana-role-binding
  namespace: logging
subjects:
- kind: ServiceAccount
  name: kibana-sa
  namespace: logging
roleRef:
  kind: Role
  name: kibana-role
  apiGroup: rbac.authorization.k8s.io
